name: Run Selenium Tests

on:
  push:
    branches:
      - main # main 브랜치로 푸시될 때 실행
  pull_request:
    branches:
      - main # PR이 main 브랜치로 열릴 때 실행

jobs:
  selenium-test:
    runs-on: ubuntu-latest # GitHub Actions에서 사용할 운영체제 (여기서는 최신 Ubuntu)

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # 사용하려는 Python 버전 (예: 3.8)

      # 3. Install dependencies (예: Selenium, WebDriver Manager 등)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager  # selenium, webdriver-manager 설치

      # 4. Run your test file (여기서 test.py는 테스트 스크립트 파일입니다)
      - name: Run tests
        run: |
          python test.py  # 실제 테스트를 실행
