name: Run Tests

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행
  pull_request:
    branches:
      - main # main 브랜치로 PR을 보낼 때마다 실행

jobs:
  test:
    runs-on: ubuntu-latest # GitHub Actions에서 사용할 운영체제 (여기선 Ubuntu)

    steps:
      # 1단계: 레포지토리 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2단계: Python 설정
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Python 3 버전 설정

      # 3단계: 필요한 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4단계: 테스트 실행
      - name: Run Tests
        run: |
          python -m unittest discover -s src/features -p "test_*.py"
